_BASE_: "./t3_train_distill.yaml"
OUTPUT_DIR: "./output/t3_replay_distill"
MODEL:
  WEIGHTS: "./output/t3_distill/model_final.pth"
SOLVER:
  STEPS: (110000, 112000)
  MAX_ITER: 116500
  WARMUP_ITERS: 0
OWOD:
  ENABLE_CLUSTERING: False
  INCREMENTAL:
    DISTILLATION:
      ENABLED: True
      TEACHER_WEIGHTS: "./output/t2_distill/model_final.pth"
      TEMPERATURE: 2.0
      CLS_WEIGHT: 1.0
      BBOX_WEIGHT: 1.0
    REPLAY:
      ENABLED: True
      TRAIN_DATASET: "t3_voc_coco_2007_ft"
