from detectron2.config import CfgNode as CN


def add_param_iso_config(cfg):
    if not hasattr(cfg, "OWOD"):
        cfg.OWOD = CN()

    if not hasattr(cfg.OWOD, "INCREMENTAL"):
        cfg.OWOD.INCREMENTAL = CN()

    if not hasattr(cfg.OWOD.INCREMENTAL, "PARAM_ISOLATION"):
        cfg.OWOD.INCREMENTAL.PARAM_ISOLATION = CN()

    cfg.OWOD.INCREMENTAL.PARAM_ISOLATION.ENABLED = False
    cfg.OWOD.INCREMENTAL.PARAM_ISOLATION.FREEZE_BACKBONE = False
    cfg.OWOD.INCREMENTAL.PARAM_ISOLATION.FREEZE_PROPOSAL_GENERATOR = False
    cfg.OWOD.INCREMENTAL.PARAM_ISOLATION.FREEZE_ROI_BOX_FEATURE_EXTRACTOR = False
    cfg.OWOD.INCREMENTAL.PARAM_ISOLATION.FREEZE_OLD_CLASSIFIER = False
    cfg.OWOD.INCREMENTAL.PARAM_ISOLATION.FREEZE_OLD_BBOX_REG = False
